GET http://localhost:5000/api/vi/products
Content-Type: application/json
###

GET http://localhost:5000/api/vi/products?keyword=Product&price=200
Content-Type: application/json
###

GET http://localhost:5000/api/vi/products?keyword=Product&price[lte]=200
Content-Type: application/json
###

GET http://localhost:5000/api/vi/products?page=2
Content-Type: application/json
###

POST http://localhost:5000/api/vi/product/new
Content-Type: application/json

{
    "summary": "Product 2 description",
    "price": 100,
    "category": "category 1",
    "images": {
        "public_id": "sample_id",
        "url": "sample_url"
    }
}
###

PUT http://localhost:5000/api/vi/product/638b57cf7f001b4b51ebc70a
Content-Type: application/json

{
    "title": "Product 1",
    "summary": "Product 1 description changed",
    "price": 200,
    "category": "category 1",
    "images": {
        "public_id": "sample_id",
        "url": "sample_url"
    }
}
###

DELETE http://localhost:5000/api/vi/product/638b654d2cbedb5e39d5cc3b
Content-Type: application/json


###

GET http://localhost:5000/api/vi/product/638b62a3e45ec567d3535d20
Content-Type: application/json


###

POST http://localhost:5000/api/vi/register
Content-Type: application/json

{
    "name": "User 1",
    "email": "user@boutique.com",
    "password": "user1",
    "role": "user"
}

###

POST http://localhost:5000/api/vi/register
Content-Type: application/json

{
    "name": "Noor",
    "email": "lnsworld.13@gmail.com",
    "password": "lnoor",
    "role": "user"
}

###
POST http://localhost:5000/api/vi/login
Content-Type: application/json

{
    "email":"lnsworld.13@gmail.com",
    "password":"lnoor1"

}
###

POST http://localhost:5000/api/vi/login
Content-Type: application/json

{
    "email":"admin@boutique.com",
    "password":"admin"

}
###

GET http://localhost:5000/api/vi/me
Content-Type: application/json

###

GET http://localhost:5000/api/vi/logout
Content-Type: application/json

###

GET http://localhost:5000/api/vi/users
Content-Type: application/json

###

POST http://localhost:5000/api/vi/password/forgot
Content-Type: application/json

{
    "email":"lnsworld.13@gmail.com"

}

###

PUT http://localhost:5000/api/vi/password/update
Content-Type: application/json

{
    "oldPassword": "lnoor",
    "newPassword": "lnoor1",
    "confirmPassword": "lnoor1"
}